"use client";

import { useEffect, useMemo, useState } from "react";
import JSZip from "jszip";
import Navbar from "@/components/ui/navbar";
import { PromptInputBox } from "@/components/ui/ai-prompt-box";
import { ProjectExplorer } from "@/components/ui/project-explorer";
import { normalizeProjectTree, type ProjectNode } from "@/lib/project-tree";

function getDefaultFileContent(filePath: string, projectName: string) {
  if (filePath.endsWith("package.json")) {
    return JSON.stringify(
      {
        name: projectName,
        version: "0.1.0",
        private: true,
        scripts: {
          dev: "next dev",
          build: "next build",
          start: "next start",
        },
      },
      null,
      2,
    );
  }

  if (filePath.endsWith("tsconfig.json")) {
    return JSON.stringify(
      {
        compilerOptions: {
          target: "ES2017",
          lib: ["dom", "dom.iterable", "esnext"],
          allowJs: true,
          skipLibCheck: true,
          strict: true,
          noEmit: true,
          esModuleInterop: true,
          module: "esnext",
          moduleResolution: "bundler",
          resolveJsonModule: true,
          isolatedModules: true,
          jsx: "preserve",
          incremental: true,
          plugins: [{ name: "next" }],
        },
        include: ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],
        exclude: ["node_modules"],
      },
      null,
      2,
    );
  }

  if (filePath.endsWith("README.md")) {
    return `# ${projectName}\n\nGenerated with EaseFolder.`;
  }

  if (filePath.endsWith("layout.tsx")) {
    return `import type { Metadata } from "next";\nimport "./globals.css";\n\nexport const metadata: Metadata = {\n  title: "${projectName}",\n  description: "Generated by EaseFolder",\n};\n\nexport default function RootLayout({ children }: LayoutProps<"/">) {\n  return (\n    <html lang="en">\n      <body>{children}</body>\n    </html>\n  );\n}`;
  }

  if (filePath.endsWith("page.tsx")) {
    return `export default function Page() {\n  return <main>${projectName}</main>;\n}`;
  }

  if (filePath.endsWith("globals.css")) {
    return `body {\n  margin: 0;\n  font-family: sans-serif;\n}`;
  }

  if (filePath.endsWith(".css")) {
    return `/* ${filePath} */`;
  }

  if (filePath.endsWith(".tsx") || filePath.endsWith(".ts")) {
    return `// ${filePath}\n`;
  }

  return "";
}

async function exportProjectZip(projectName: string, tree: ProjectNode[]) {
  const zip = new JSZip();
  const root = zip.folder(projectName);

  if (!root) {
    throw new Error("Unable to create zip root folder.");
  }

  const appendNodes = (
    currentZip: JSZip,
    currentNodes: ProjectNode[],
    currentPath: string,
  ) => {
    currentNodes.forEach((node) => {
      if (node.type === "folder") {
        const folder = currentZip.folder(node.name);

        if (folder && node.children?.length) {
          appendNodes(folder, node.children, `${currentPath}/${node.name}`);
        }

        return;
      }

      const filePath = `${currentPath}/${node.name}`;
      currentZip.file(node.name, getDefaultFileContent(filePath, projectName));
    });
  };

  appendNodes(root, tree, projectName);

  const blob = await zip.generateAsync({
    type: "blob",
    compression: "DEFLATE",
    compressionOptions: {
      level: 9,
    },
  });

  const downloadUrl = URL.createObjectURL(blob);
  const anchor = document.createElement("a");
  anchor.href = downloadUrl;
  anchor.download = `${projectName}.zip`;
  anchor.click();
  URL.revokeObjectURL(downloadUrl);
}

export default function CreatePage() {
  const [messages, setMessages] = useState<string[]>([
    "Start by telling me what you want to build.",
  ]);
  const [projectId, setProjectId] = useState<string>("");
  const [isSessionReady, setIsSessionReady] = useState(false);
  const [isSubmitting, setIsSubmitting] = useState(false);

  const [projectTree, setProjectTree] = useState<ProjectNode[]>(() =>
    normalizeProjectTree([
      {
        name: "app",
        type: "folder",
        children: [
          { name: "layout.tsx", type: "file" },
          { name: "page.tsx", type: "file" },
          { name: "globals.css", type: "file" },
        ],
      },
      {
        name: "components",
        type: "folder",
        children: [],
      },
      {
        name: "lib",
        type: "folder",
        children: [],
      },
      {
        name: "public",
        type: "folder",
        children: [],
      },
      { name: "package.json", type: "file" },
      { name: "tsconfig.json", type: "file" },
      { name: "README.md", type: "file" },
    ]),
  );
  const [isExporting, setIsExporting] = useState(false);

  const projectSnapshot = useMemo(
    () => ({
      projectName: "my-next-app",
      description: "",
      stack: {
        framework: "Next.js",
        language: "TypeScript",
        styling: "Tailwind CSS",
      },
      tree: projectTree,
    }),
    [projectTree],
  );

  useEffect(() => {
    const storedProjectId = sessionStorage.getItem("easefolder-project-id");

    if (storedProjectId) {
      setProjectId(storedProjectId);
      setIsSessionReady(true);
      return;
    }

    const generatedProjectId = crypto.randomUUID();
    sessionStorage.setItem("easefolder-project-id", generatedProjectId);
    setProjectId(generatedProjectId);
    setIsSessionReady(true);
  }, []);

  useEffect(() => {
    if (!isSessionReady || !projectId) {
      return;
    }

    const syncTimer = window.setTimeout(() => {
      void fetch("/api/project/session", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          projectId,
          projectSnapshot,
        }),
      });
    }, 250);

    return () => window.clearTimeout(syncTimer);
  }, [isSessionReady, projectId, projectSnapshot]);

  useEffect(() => {
    const latestMessageAnchor = document.getElementById("latest-message-anchor");

    latestMessageAnchor?.scrollIntoView({
      behavior: isSubmitting ? "auto" : "smooth",
      block: "end",
    });
  }, [messages, isSubmitting]);

  const handleSendMessage = async (message: string) => {
    if (!projectId || isSubmitting) {
      return;
    }

    setIsSubmitting(true);
    setMessages((current) => [...current, message, "Thinking..."]);

    try {
      const response = await fetch("/api/ai/chat", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          projectId,
          message,
          projectSnapshot,
        }),
      });

      const payload = (await response.json()) as {
        message?: string;
        tree?: ProjectNode[];
        error?: string;
      };

      if (!response.ok) {
        throw new Error(payload.error ?? "Unable to reach the AI service.");
      }

      if (payload.tree) {
        setProjectTree(payload.tree);
      }

      setMessages((current) => {
        const nextMessages = [...current];

        if (nextMessages[nextMessages.length - 1] === "Thinking...") {
          nextMessages[nextMessages.length - 1] =
            payload.message ?? "I updated the project structure.";
        } else {
          nextMessages.push(payload.message ?? "I updated the project structure.");
        }

        return nextMessages;
      });
    } catch (error) {
      const errorMessage =
        error instanceof Error ? error.message : "Unable to reach the AI service.";

      setMessages((current) => {
        const nextMessages = [...current];

        if (nextMessages[nextMessages.length - 1] === "Thinking...") {
          nextMessages[nextMessages.length - 1] = errorMessage;
        } else {
          nextMessages.push(errorMessage);
        }

        return nextMessages;
      });
    } finally {
      setIsSubmitting(false);
    }
  };

  const handleExportZip = async () => {
    if (isExporting) {
      return;
    }

    setIsExporting(true);

    try {
      await exportProjectZip("my-next-app", projectTree);
    } finally {
      setIsExporting(false);
    }
  };

  return (
    <div className="min-h-screen px-3 py-2 sm:px-6 lg:px-8">
      <Navbar isLightMode={true} />
      <main className="mx-auto flex h-[calc(100vh-1rem)] max-w-4xl flex-col border-dotted border-white/15 px-4 pb-4 pt-24 sm:px-6 sm:pt-28 md:border-x">
        <div className="flex h-full min-h-0 flex-col overflow-hidden rounded-[2rem] border border-white/10 bg-[#0b0b0b] shadow-[0_22px_70px_rgba(0,0,0,0.38)]">
          <div className="grid h-full min-h-0 flex-1 lg:grid-cols-[380px_minmax(0,1fr)]">
            <aside className="flex h-full min-h-0 w-full flex-col overflow-hidden border-b border-white/8 bg-[#111111] p-4 text-white lg:border-b-0 lg:border-r">
              <div className="mb-4 flex items-center justify-between">
                <div>
                  <p className="text-xs uppercase tracking-[0.35em] text-white/45">
                    Workspace
                  </p>
                  <h1 className="mt-2 font-heading text-2xl font-bold">
                    EaseFolder AI
                  </h1>
                </div>
              </div>

              <div className="scrollbar-none flex min-h-0 flex-1 flex-col gap-3 overflow-y-auto pr-1">
                {messages.map((message, index) => {
                  const isThinkingMessage =
                    isSubmitting &&
                    index === messages.length - 1 &&
                    message === "Thinking...";

                  return (
                    <div
                      key={index}
                      className={`flex items-end gap-2 ${
                        index % 2 === 0 ? "justify-start" : "justify-end"
                      }`}
                    >
                      {index % 2 === 0 ? (
                        <img
                          src="/logo.png"
                          alt="EaseFolder"
                          className="h-6 w-6 shrink-0 rounded-full border border-white/10 object-cover"
                        />
                      ) : null}
                      <div
                        className={`max-w-[85%] rounded-[1.25rem] px-4 py-3 text-sm leading-6 transition duration-200 hover:-translate-y-0.5 ${
                          index % 2 === 0
                            ? "bg-white/6 text-white"
                            : "bg-white/12 text-white"
                        }`}
                      >
                        {isThinkingMessage ? (
                          <span className="text-shimmer font-medium">
                            Thinking...
                          </span>
                        ) : (
                          message
                        )}
                      </div>
                    </div>
                  );
                })}
                <div id="latest-message-anchor" />
              </div>

              <div className="mt-4">
                <PromptInputBox
                  placeholder="Ask the AI to create a project structure..."
                  className="border-white/8 bg-[#151515]"
                  isSubmitting={isSubmitting}
                  onSend={handleSendMessage}
                />
              </div>
            </aside>

            <section className="flex h-full min-h-0 flex-1 flex-col overflow-hidden bg-[linear-gradient(180deg,rgba(255,255,255,0.03)_0%,rgba(8,8,8,1)_100%)] p-4 text-white sm:p-6">
              <div className="mb-4 flex items-center justify-between">
                <div>
                  <p className="text-xs uppercase tracking-[0.35em] text-white/45">
                    Folder Preview
                  </p>
                  <h2 className="mt-2 font-heading text-2xl font-bold sm:text-3xl">
                    Live folder preview
                  </h2>
                </div>
                <button
                  type="button"
                  onClick={handleExportZip}
                  disabled={isExporting}
                  className="rounded-xl border border-white/70 bg-white px-4 py-2 text-sm font-semibold text-[#101114] shadow-[0_14px_35px_rgba(255,255,255,0.16)] transition duration-200 hover:-translate-y-0.5 hover:bg-white/90 disabled:cursor-not-allowed disabled:opacity-70"
                >
                  {isExporting ? "Exporting..." : "Export ZIP"}
                </button>
              </div>

              <ProjectExplorer
                projectName="my-next-app"
                tree={projectTree}
                onChange={setProjectTree}
                className="min-h-0 flex-1"
              />
            </section>
          </div>
        </div>
      </main>
    </div>
  );
}
